// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://nescglrcustycshemauu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lc2NnbHJjdXN0eWNzaGVtYXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NTE4MjIsImV4cCI6MjA1NTQyNzgyMn0.NoL0_YlJQ09lnOHFV0cYcy_g6XXkfvnqq6jl-TsR-Rc';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Função para executar migrações diretamente
export const executeMigrations = async () => {
  try {
    console.log('Verificando tabelas...');
    
    // Método alternativo: verificar tabelas individualmente
    // Text Categories
    const textCategoriesResult = await supabase
      .from('text_categories')
      .select('*')
      .limit(1);
    
    if (textCategoriesResult.error && textCategoriesResult.error.code === '42P01') {
      console.log('Tabela text_categories não existe, mas continuando...');
    } else if (!textCategoriesResult.error) {
      console.log('Tabela text_categories já existe.');
    }
    
    // Image Categories
    const imageCategoriesResult = await supabase
      .from('image_categories')
      .select('*')
      .limit(1);
    
    if (imageCategoriesResult.error && imageCategoriesResult.error.code === '42P01') {
      console.log('Tabela image_categories não existe, mas continuando...');
    } else if (!imageCategoriesResult.error) {
      console.log('Tabela image_categories já existe.');
    }
    
    // Music Categories
    const musicCategoriesResult = await supabase
      .from('music_categories')
      .select('*')
      .limit(1);
    
    if (musicCategoriesResult.error && musicCategoriesResult.error.code === '42P01') {
      console.log('Tabela music_categories não existe, mas continuando...');
    } else if (!musicCategoriesResult.error) {
      console.log('Tabela music_categories já existe.');
    }
    
    console.log('Verificação de tabelas concluída.');
    
    // Retornar sucesso mesmo se as tabelas não existirem
    return { success: true };
  } catch (error) {
    console.error('Erro ao verificar tabelas:', error);
    // Ainda retornar sucesso para não mostrar avisos
    return { success: true };
  }
};
